"""
Attack simulation: Ciphertext tampering
=========================================

Scenario
--------
Mallory intercepts a valid encrypted message between Alice and Bob.
She cannot decrypt it (no session key), but she tries to alter the raw
ciphertext bytes and forward the modified frame, hoping to change the
decrypted plaintext.

Defence layer 1 — AES-256-GCM authentication tag
-------------------------------------------------
GCM produces a 16-byte authentication tag that is a MAC over the
ciphertext + nonce + (optional) associated data.  Any single bit flip in
the ciphertext invalidates the tag.  Decryption raises InvalidTag before
returning any plaintext.

Defence layer 2 — RSA-PSS digital signature
--------------------------------------------
The sender signs the raw ciphertext bytes.  Even if Mallory replaced the
entire ciphertext with freshly generated bytes (from her own AES key), the
RSA-PSS signature over the *original* ciphertext would no longer verify.
She cannot produce a valid signature without Alice's private key.

Three tampering attempts are demonstrated:
  A) Single bit-flip in the ciphertext body
  B) Truncation of the ciphertext (remove last byte)
  C) Full ciphertext replacement with Mallory's own encryption

Run:
    python -m attacks.tamper
    # or from the project root:
    python attacks/tamper.py
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import crypto_utils as cu
from cryptography.exceptions import InvalidTag

RESET  = "\033[0m"
RED    = "\033[31m"
GREEN  = "\033[32m"
YELLOW = "\033[33m"
CYAN   = "\033[36m"
BOLD   = "\033[1m"

def section(title: str) -> None:
    print(f"\n{BOLD}{CYAN}{'─'*60}{RESET}")
    print(f"{BOLD}{CYAN}  {title}{RESET}")
    print(f"{BOLD}{CYAN}{'─'*60}{RESET}\n")

def log(actor: str, msg: str, color: str = RESET) -> None:
    print(f"  {BOLD}{color}[{actor:^8}]{RESET}  {msg}")


def try_receive(session_key: bytes, sender_pub, nonce: bytes, ciphertext: bytes, signature: bytes) -> None:
    """Attempt to decrypt and verify. Print the result."""
    # Layer 1: AES-GCM authentication
    try:
        plaintext = cu.aes_decrypt(session_key, nonce, ciphertext)
        gcm_ok = True
    except InvalidTag:
        log("Bob", f"{RED}AES-GCM auth tag FAILED — ciphertext was tampered!{RESET}", RED)
        gcm_ok = False

    if not gcm_ok:
        # Signature check is moot if we can't even decrypt
        sig_ok = cu.verify(sender_pub, ciphertext, signature)
        log("Bob", f"RSA-PSS signature check: {'valid' if sig_ok else 'INVALID'}", YELLOW)
        print(f"  {BOLD}{GREEN}  ✓  Tampering detected — message dropped.{RESET}")
        return

    # Layer 2: RSA-PSS signature
    sig_ok = cu.verify(sender_pub, ciphertext, signature)
    if sig_ok:
        log("Bob", f"decrypted: '{plaintext.decode()}'  |  signature: VALID", GREEN)
    else:
        log("Bob", f"decrypted: '{plaintext.decode()}'  |  signature: {RED}INVALID ⚠{RESET}", YELLOW)
        print(f"  {BOLD}{GREEN}  ✓  Tampering detected via signature — message rejected.{RESET}")


def main() -> None:
    print(f"\n{BOLD}Ciphertext Tampering Attack Simulation{RESET}")
    print("=" * 60)

    # ------------------------------------------------------------------ #
    # Setup: establish honest session                                     #
    # ------------------------------------------------------------------ #
    section("1 · Setup — honest session established")

    alice_priv, alice_pub = cu.generate_rsa_keypair()
    session_key = cu.generate_aes_key()

    original_text = "Transfer $200 to Alice"
    nonce, ciphertext = cu.aes_encrypt(session_key, original_text.encode())
    signature = cu.sign(alice_priv, ciphertext)

    log("Alice", f"plaintext:  '{original_text}'",              GREEN)
    log("Alice", f"ciphertext: {ciphertext.hex()[:32]}…",       GREEN)
    log("Alice", f"signature:  {signature.hex()[:24]}…",        GREEN)
    log("Bob",   "receives and verifies the honest message…",   GREEN)
    try_receive(session_key, alice_pub, nonce, ciphertext, signature)

    # ------------------------------------------------------------------ #
    # Attack A: bit-flip a single byte in the ciphertext                 #
    # ------------------------------------------------------------------ #
    section("2 · Attack A — single byte bit-flip")

    tampered_a = bytearray(ciphertext)
    tampered_a[0] ^= 0xFF                     # flip all bits in byte 0
    tampered_a = bytes(tampered_a)

    log("Mallory", f"original  byte[0]: 0x{ciphertext[0]:02x}",  RED)
    log("Mallory", f"flipped   byte[0]: 0x{tampered_a[0]:02x}",  RED)
    log("Mallory", "forwards tampered ciphertext to Bob…",        RED)
    try_receive(session_key, alice_pub, nonce, tampered_a, signature)

    # ------------------------------------------------------------------ #
    # Attack B: truncate the ciphertext (drop last byte)                 #
    # ------------------------------------------------------------------ #
    section("3 · Attack B — truncation (drop last byte)")

    tampered_b = ciphertext[:-1]

    log("Mallory", f"original length:  {len(ciphertext)} bytes", RED)
    log("Mallory", f"truncated length: {len(tampered_b)} bytes", RED)
    log("Mallory", "forwards truncated ciphertext to Bob…",       RED)
    try_receive(session_key, alice_pub, nonce, tampered_b, signature)

    # ------------------------------------------------------------------ #
    # Attack C: full ciphertext replacement                              #
    # ------------------------------------------------------------------ #
    section("4 · Attack C — full replacement with Mallory's own encryption")

    # Mallory doesn't know the session key, so she uses her own
    mallory_key = cu.generate_aes_key()
    forged_text = "Transfer $200 to Mallory"
    new_nonce, forged_ct = cu.aes_encrypt(mallory_key, forged_text.encode())

    # She keeps Alice's original signature (she can't produce a valid one)
    log("Mallory", f"forges ciphertext for: '{forged_text}'", RED)
    log("Mallory", "re-uses Alice's original signature…",      RED)
    log("Mallory", "forwards forged frame to Bob…",            RED)

    # Bob's session key is different from Mallory's key → GCM tag fails
    try_receive(session_key, alice_pub, new_nonce, forged_ct, signature)

    # ------------------------------------------------------------------ #
    # Extra: show that signature catches it even if GCM somehow passed  #
    # ------------------------------------------------------------------ #
    section("5 · Signature check in isolation (hypothetical)")

    print("  Suppose GCM auth were somehow bypassed — the RSA-PSS signature")
    print("  is computed over the *original* ciphertext bytes.")
    print("  Checking Alice's signature against the forged ciphertext:\n")

    sig_result = cu.verify(alice_pub, forged_ct, signature)
    log("Bob", f"verify(alice_pub, forged_ct, alice_sig) → {sig_result}", YELLOW)
    print(f"\n  {BOLD}{GREEN}  ✓  Signature does not verify — second layer of defence holds.{RESET}")

    section("Summary")
    print("  Two independent defences prevent ciphertext tampering:\n")
    print("    1. AES-256-GCM authentication tag")
    print("       • Covers every bit of the ciphertext + nonce")
    print("       • Any modification → InvalidTag before plaintext is returned")
    print()
    print("    2. RSA-PSS digital signature (sign-then-encrypt order: sign AFTER encrypt)")
    print("       • Signed over the raw ciphertext, not the plaintext")
    print("       • Attacker cannot forge a valid signature without the sender's private key")
    print()
    print("  Together they provide authenticated encryption — confidentiality,")
    print("  integrity, and authenticity in a single pass.\n")


if __name__ == "__main__":
    main()
